### ISSUE TITLE
can't see the column search volume in search console

### ISSUE THREAD

**Issue by ukottig** [antoineeripret/google_search_console_search_volume#7] opened 2021-06-30 10:05 UTC
Hi Antoin,

as mentioned on LinkedIn I added your chrome plugin, changed the language to DE.

But even after reload, cache delete and relogin I can't see the new column.

![Screenshot 2021-06-30 120103](https://user-images.githubusercontent.com/45765997/123942516-80438900-d99b-11eb-905b-9d995b4509ad.jpg)

**Comment by antoineeripret** [comment] 2021-06-30 10:11
Hi @ukottig, 

Thanks for reporting the issue. 

Can you follow these steps please: 

- Open one of your GSC properties 
- Open Chrome Developer Tools (https://balsamiq.com/support/faqs/browserconsole/)
- Reload the page while having this open 
- Wait a bit, go to the "Network tab" and look for "surfer" 

![image](https://user-images.githubusercontent.com/9512616/123942975-f2b46900-d99b-11eb-8b33-84b75706534c.png)

Can you then tell me if you have requests in red or in black (meaning if they has failed or succeeded) and copy the URL for the first requests? 

For transparency, please note that I'm fairly confident that the issue is caused by a special carácter (like in #6), but I need the URL to double-check that.  

Thanks.

**Comment by ukottig** [comment] 2021-06-30 10:18
Hi,
yes, it is red, and here the URL
https://db2.keywordsur.fr/keyword_surfer_keywords?country=de&keywords=[%22oee%22,%22trebing%20himstedt%22,%22trebing%20&%20himstedt%20proze%C3%9Fautomation%20gmbh%20&%20co.%20kg%22,%22oee%20bedeutung%22,%22trebing%20und%20himstedt%22,%22oee%20kennzahl%22,%22sap%20ain%22,%22oee%20definition%22,%22sap%20pco%22,%22oee%20berechnung%22,%22sap%20dmc%22,%22oee-rechner%22,%22trebing%20&%20himstedt%22,%22trebing%20+%20himstedt%22,%22oee%20rechner%22,%22sap%20mii%22,%22oee%20definition%20deutsch%22,%22oee%20formel%22,%22was%20bedeutet%20oee%22,%22sap%20asset%20intelligence%20network%22,%22oee%20berechnen%22,%22sap%20pai%22,%22sap%20pico%22,%22oee%20deutsch%22,%22nutzungsgrad%20rechner%22,%22trebing%22,%22asset%20intelligence%20network%22,%22pco%20sap%22,%22sap%20digital%20manufacturing%20cloud%22,%22berechnung%20oee%22,%22ain%20sap%22,%22kennzahl%20oee%22,%22oee%20erkl%C3%A4rung%22,%22was%20bieten%20wir%20unseren%20mitarbeitern%22,%22sap%20predictive%20asset%20insights%22,%22t+h%22,%22microsoft%20clarity%20datenschutzerkl%C3%A4rung%22,%22sap%20dmci%22,%22oee%20kennzahl%20definition%22,%22sap%20shop%20floor%22,%22sap%20iot%22,%22oee%20abk%C3%BCrzung%22,%22oee%20berechnung%20formel%22,%22definition%20oee%20kennzahl%22,%22gesamtanlageneffektivit%C3%A4t%22,%22microsoft%20clarity%20dsgvo%22,%22produktr%C3%BCckverfolgbarkeit%22,%22sap%20dmce%22,%22sap%20me%22,%22overall%20equipment%20effectiveness%22]

**Comment by antoineeripret** [comment] 2021-06-30 10:24
Thanks @ukottig !

You have the same issue raised in #6. Some of your keywords include "&", which breaks the API. I didn't anticipate it in the first version and I have to submit a change (already in Github) to Google Chrome Store. 

I'll be on holidays starting this Friday and I'll do it when I go back, so you'll unfortunately have to wait several weeks to use my extension for your property. 

![image](https://user-images.githubusercontent.com/9512616/123944930-ec26f100-d99d-11eb-809e-bbf2059668a6.png)

Thanks again for reporting.

**Comment by ukottig** [comment] 2021-06-30 10:28
ok, great, thx!

**Comment by antoineeripret** [comment] 2021-07-21 11:34
@ukottig: change applied and submitted for review to the Chrome Store (version 0.2). Thanks for reporting it!

**Comment by ukottig** [comment] 2021-07-26 14:32
hi @antoineeripret,

I use the V 0.2 as far as I can see, but it is still not working, I get this error message:
`"Failed while parsing JSON keywords array"`

![Screenshot 2021-07-26 163018](https://user-images.githubusercontent.com/45765997/127006212-bc517669-8f38-4bed-b0e5-a1e4f30b8152.jpg)


https://db2.keywordsur.fr/keyword_surfer_keywords?country=de&keywords=[%22oee%22,%22trebing%20himstedt%22,%22trebing%20%20himstedt%20proze%C3%9Fautomation%20gmbh%20&%20co.%20kg%22,%22trebing%20und%20himstedt%22,%22oee%20kennzahl%22,%22oee%20bedeutung%22,%22sap%20ain%22,%22sap%20pco%22,%22oee%20definition%22,%22sap%20dmc%22,%22oee%20berechnung%22,%22trebing%20%20himstedt%22,%22oee-rechner%22,%22sap%20mii%22,%22oee%20formel%22,%22trebing%20+%20himstedt%22,%22oee%20rechner%22,%22sap%20pai%22,%22sap%20pico%22,%22oee%20definition%20deutsch%22,%22was%20bedeutet%20oee%22,%22oee%20berechnen%22,%22asset%20intelligence%20network%22,%22sap%20asset%20intelligence%20network%22,%22oee%20deutsch%22,%22ain%20sap%22,%22trebing%22,%22sap%20dmci%22,%22kennzahl%20oee%22,%22pco%20sap%22,%22was%20bieten%20wir%20unseren%20mitarbeitern%22,%22nutzungsgrad%20rechner%22,%22berechnung%20oee%22,%22gesamtanlageneffektivit%C3%A4t%22,%22sap%20predictive%20asset%20insights%22,%22oee%20erkl%C3%A4rung%22,%22oee%20kennzahl%20definition%22,%22sap%20digital%20manufacturing%20cloud%22,%22t+h%22,%22oee%20berechnung%20formel%22,%22steffen%20himstedt%22,%22definition%20oee%20kennzahl%22,%22sap%20dmce%22,%22pco%20server%22,%22overall%20equipment%20effectiveness%22,%22was%20ist%20oee%22,%22oee%20kennzahlen%22,%22microsoft%20clarity%20datenschutzerkl%C3%A4rung%22,%22ope%20berechnen%22,%22sap%20me%22]

**Comment by antoineeripret** [comment] 2021-07-29 13:53
@ukottig: I see what is happening and just fixed it (in GitHub, not live yet). 

One question: do you think you could share the GSC access with me, to be sure that it will now be working for you? I would completely understand if you can't, but debugging is harder for me because I do not have any web property with the issues you are facing :/

**Comment by ukottig** [comment] 2021-07-29 14:50
Hi,
yes, I would temporary share it, no problem, but I am on vacation the next two weeks, so if necessary we could do it after the 16th of august.

**Comment by antoineeripret** [comment] 2021-07-30 09:33
@ukottig: let me know when you return from your holidays then, and we'll have a look. Enjoy :)

**Comment by ukottig** [comment] 2021-08-16 14:05
@antoineeripret I am back to work and happy to look for a solution.

**Comment by antoineeripret** [comment] 2021-08-17 07:19
@ukottig, can you grant me access to your GSC property using antoine dot eripret at gmail dot com? I'll have a look this week and try to make it work :)

**Comment by ukottig** [comment] 2021-08-17 07:30
done

**Comment by antoineeripret** [comment] 2021-08-17 08:08
Thanks @ukottig. I'll let you know when I have the fix ready :)

**Comment by antoineeripret** [comment] 2021-08-17 13:05
@ukottig: the fix was easier than expected. It's now working with your property :) 

![image](https://user-images.githubusercontent.com/9512616/129730439-bc90a9e1-4ef4-493e-bc61-578e7872b13b.png)

Nevertheless, I won't publish the fix this week because I'm working on a Semrush integration and I'd like to publish it as the same time. I hope to have it ready this week and publish it during the next one. 

You can withdraw me from your property now, thanks for the help :)

**Comment by ukottig** [comment] 2021-08-17 14:11
great! awaiting the update. thx!

**Comment by antoineeripret** [comment] 2021-08-20 07:07
@ukottig: v0.3 launched, I'm closing this issue. Please reopen it if needed but it should work now :)

**Closed by antoineeripret** 2021-08-20 07:07 UTC
